### ISSUE TITLE
Access to Nette\DI\Container methods

### ISSUE THREAD

**Issue by o5** [o2ps/SlimNetteBridge#2]
Hello, 

I would like to access public methods like `getParameters()`, etc. Is it possible?

As a workaround, I added magic method `__call()` to `Oops\SlimNetteBridge\Container\ContainerAdapter`

```php
public function __call($name, $arguments)
{
     return Nette\Utils\Callback::invokeArgs([$this->container, $name], $arguments);
}
```

If is there a preferred way to do this, please tell me how, otherwise I'm able to send PR.

Thanks
Peter

**Comment by jiripudil** [comment]
Hello, the `ContainerAdapter` is there merely because of Slim and should not even be exposed (at least not via autowiring).

What is your use case? If you need to pass parameters around, you can use the features of Nette DI container:

```yml
slim:
    configurators:
        - My\App\Configurator

parameters:
    param: value

services:
    - My\App\Controller(%param%)
```

```php
namespace My\App;

class Configurator implements ApplicationConfigurator
{
    private $controller;

    public function __construct(Controller $controller)
    {
        $this->controller = $controller;
    }

    public function configureApplication(App $application): void
    {
        $application->post('/foo', $this->controller);
    }
}
```

```php
namespace My\App;

class Controller
{
    public function __construct($parameter)
    {
        $this->parameter = $parameter;
    }

    public function __invoke(RequestInterface $request, ResponseInterface $response): ResponseInterface
    {
        // here you have access to $this->parameter
        return $response;
    }
}
```

**Comment by o5** [comment]
Yes, that should work. 

But I would like to have one Controller with more actions. I need to define routes like:
```php
$application->post('/foo', My\App\Controller::class . 'fooAction');
```
and then I think there is no way to access to the parameters in Controller.

> should not even be exposed (at least not via autowiring)

Why? Because of testing? I do not plan to write unit test of controllers with database mock or something like this. I prefer to write integration tests with "real" database connection which is possible with Docker.

Maybe I'm something missing, I'm coming from `silex/silex` :)

**Comment by jiripudil** [comment]
`ContainerAdapter` as an implementation of PSR-11 is there only because Slim needs it; it provides access to the [services required by Slim](https://github.com/slimphp/Slim/blob/403b7980e0bc19ca43015f6232259d81479b24b2/Slim/DefaultServicesProvider.php), in a very specific way that pretty much prevents it from being used for anything else. Therefore I tried to keep it as internal as possible which is why it's not autowired.

> But I would like to have one Controller with more actions. I need to define routes like (...)

The route accepts any callable, so you can do this:

```php
$application->post('/foo', [$this->controller, 'fooAction']);
```

> I do not plan to write unit test of controllers with database mock or something like this. I prefer to write integration tests with "real" database connection which is possible with Docker.

No problema! The whole point of this package is to provide a bridge between Slim and Nette DI, so I find it natural to use Nette DI to its full extent. The PSR-11 thing is simply an implementation detail and you shouldn't even know it's there :)

**Comment by o5** [comment]
Thank you for explanation, I'll use my fork :)
