### ISSUE TITLE
nette/bootstrap

### ISSUE THREAD

**Issue by Huholoman** [o2ps/SlimNetteBridge#4]
Move nette/bootstrap from require-dev to require?

**Comment by jiripudil** [comment]
Hello, thanks for the suggestion, but I'm not going to do it because it is not strictly required nor directly used by this package. While using nette/bootstrap is very practical as opposed to constructing the DI container by hand, the choice to use it is entirely yours.

I consider this issue resolved so I'm closing it, but feel free to ask further if you have any questions
